<div class="titulo">A&ccedil;&otilde;es</div>
<div id="tabela">
    <div><a href="<?php echo $this->baseUrl("comarca/form") ?>"><input type="button" value="INCLUIR"/></a></div>
    <table class="dataTable" width="100%">
         <thead>
            <tr>
            <th>Tipo da A&ccedil;&atilde;o</th>
            <th>Descri&ccedil;&atilde;o</th>
            <th>Ativo</th>
            <th>A&ccedil;&atilde;o</th>
            </tr>
    </thead>
    <tbody>
            <?php foreach ($this->comarca as $comarca): ?>
            <tr>
            <td><?php echo $comarca['CODIGO']?></td>
            <td><?php echo $comarca['DESCRICAO']?></td>
            <td><?php if($comarca['ST_ATIVO'] == 1) echo "SIM"; else echo "NÃO"; ?></td>
            <td style="text-align:center;">
                <a href="<?php echo $this->baseUrl("comarca/form/ID_COMARCA/{$comarca['ID_COMARCA']}")?>"><input type="button" value="Alterar"/></a>
                <a href="<?php echo $this->baseUrl("comarca/deletar/ID_COMARCA/{$comarca['ID_COMARCA']}")?>"><input class="excluir" type="button" value="Excluir"/></a>
            </td>
            </tr>
            <?php endforeach; ?>
    </tbody>
    </table>
</div>