<div class="titulo">A&ccedil;&otilde;es</div>
    <div id="tabela">
        <div><a href="/acao/cadAcao"><input type="button" value="INCLUIR"/></a></div>
        <table class="dataTable" width="100%">
             <thead>
                <tr>
                <th>Tipo da A&ccedil;&atilde;o</th>
                <th>Descri&ccedil;&atilde;o</th>
                <th>Ativo</th>
                <th>A&ccedil;&atilde;o</th>
                </tr>
        </thead>
        <tbody>
        </tbody>
        </table>
    </div>
</div>
