<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
    <head>
        <title>NPJES</title>
        <meta charset="UTF-8" />


        <?php echo $this->headLink()->appendStylesheet('/stylesheet/estilo.css'); ?>
        <?php echo $this->headLink()->appendStylesheet('/stylesheet/jquery.dataTables.css');?>
        <?php echo $this->headLink()->appendStylesheet('/stylesheet/jquery-ui-1.8.21.custom.css');?>
        <?php echo $this->headLink()->appendStylesheet('/js/fullcalendar/fullcalendar.css');?>
        <?php echo $this->headLink()->appendStylesheet('/js/fullcalendar/theme.css');?>
        <?php echo $this->headLink()->appendStylesheet('/js/validation/validationEngine.jquery.css');?>
        <?php echo $this->headLink()->appendStylesheet('/js/tooltip/tipsy.css');?>
        <?php  echo $this->headMeta();
        echo $this->headTitle('Login');

       ?>
    <script type="text/javascript" src="<?php echo $this->baseUrl("/js/jquery.js")?>"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl("/js/jquery.dataTables.min.js")?>"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl("/js/dataTable.js")?>"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl("/js/calendario.js")?>"></script>
   <!--  <script type="text/javascript" src="<?php //echo $this->baseUrl("/js/agenda.js")?>"></script>-->
    <script type="text/javascript" src="<?php echo $this->baseUrl("/js/fullcalendar/fullcalendar.min.js")?>"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl("/js/fullcalendar/jquery-ui-1.8.17.custom.min.js")?>"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl("/js/jquery-ui-1.8.21.js")?>"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl("/js/jquery.validate.js")?>"></script>
     <script type="text/javascript" src="<?php echo $this->baseUrl("/js/tooltip/jquery.tipsy.js")?>"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl("/js/validation/jquery.validationEngine.js")?>"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl("/js/script.js")?>"></script>

    </head>
