<?php echo $this->doctype('XHTML1_STRICT') ?>
<html lang="pt-br">
    <head>
        <title>Login</title>
        <meta charset="UTF-8" />
        <?php echo $this->headLink()->appendStylesheet('/stylesheet/login.css'); ?>
        <?php echo $this->headLink()->appendStylesheet('/stylesheet/jquery-ui-1.8.21.custom.css');?>
        <?php  echo $this->headMeta();
        echo $this->headTitle('Login');

       ?>
    <script type="text/javascript" src="<?php echo $this->baseUrl("/js/jquery.validate.js")?>"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl("/js/scriptLoguin.js")?>"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl("/js/jquery-ui-1.8.21.js")?>"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl("/js/jquery.js")?>"></script>
    </head>
    <body>
    <?php echo $this->render('mensagens.phtml') ?>
    <form action="<?php echo $this->baseUrl("auth/login")?>" method="post">
        <div id="geral">
            <div id="topo">
                <img src="/images/logo.png" />
                <span>SGP</span><br/>
                SISTEMA DE GERENCIAMENTO DE PROCESSOS
            </div>
            <div id="linha">
                Acesso ao Sistema
                <hr/>
            </div>
            <div id="formulario">
                <div>
                    <span>Usuário</span>
                    <input type="text" class="intputTxt" value="" name="txtUsuario" id="txtUsuario" />
                </div>
                <div>
                    <span>Senha  &nbsp;</span>
                    <input type="password" class="intputTxt" value="" name="txtSenha" id="txtSenha" />
                </div>
                <div>
                    <input type="submit" value="" id="btnLogar" class="submitLoguin" name="cadastrar" />
                    <input type="button" id="btnEsqueci" class="submitEsqueci"/>
                </div>
            </div>
        </div>
    </form>
    <!-- olhar essa div abaixo -->
    <div style="display:none;">
        <div  id="dialog">
            <span>CPF:</span>
            <input type="text" id="txtCPF" class="inputTxt" value="" name="txtCPF"/>
        </div>
        <div id="senhaNova">
            <div>
                <span>Nova Senha:</span>
                <input type="text" id="txtNovaSenha" value="" name="txtNovaSenha"/>
            </div>
            <div>
                <span>Confirmação:</span>
                <input type="text" id="txtConfirmacao" value="" name="txtConfirmacao"/>
            </div>
        </div>
      </div>
    </body>
</html>