<?php echo $this->doctype('XHTML1_STRICT') ?>
<html>
    <head>
         <?php echo  $this->render('head.phtml') ?>
         <?php echo  $this->render('topo.phtml') ?>
    </head>
    <body>
        <div class="cAlign">
         <?php echo  $this->render('menu.phtml') ?>
           <div id="content" class="bordas">
                <div id="conteudo">
                    <?php echo $this->render('mensagens.phtml') ?>
                    <?php echo $this->layout()->content; ?>
                </div>
           </div>
        </div>
    </body>
</html>