<?php $session      = new Zend_Session_Namespace('app-message'); ?>
<?php $mensagens    = $session->mensagens; ?>
<?php $arrImpresso  = array();?>
<?php if (is_array($mensagens) && count($mensagens)): ?>
    <div style="padding:10px;">
        <?php foreach ($mensagens as $data): ?>

            <?php if( array_search( $data[1], $arrImpresso ) === false  ):?>
                <div class="msg msg-<?php echo $this->escape($data[0]) ?>" onclick="J(this).fadeOut('slow')">
                    <p><?php echo $this->escape($data[1]); ?></p>
                </div>
            <?php endif;?>

            <?php $arrImpresso[] = $data[1];?>
        <?php endforeach ?>
    </div>
<?php endif ?>
<?php $session->mensagens = array(); ?>
