<div id="menu" class="bordas">
    <div class="titulo">Menu</div>
    <div id="itens">
        <ul>
            <li><a class="pessoa" href="<?php echo $this->baseUrl("auth/logout")?>">PESSOAS</a></li>
            <li><a class="comarca" href="<?php echo $this->baseUrl("comarca")?>">COMARCAS</a></li>
            <li><a class="vara" href="<?php echo $this->baseUrl("vara")?>">VARAS</a></li>
            <li><a class="acao" href="<?php echo $this->baseUrl("acao")?>">AÇÕES</a></li>
            <li><a class="processo" href="<?php echo $this->baseUrl("auth/logout")?>">PROCESSOS</a></li>
        </ul>
    </div>
</div>







