<div id="topo">
    <span><?php //echo $_SESSION["usuario"]["usuario"] ?> | <a href="<?php echo $this->baseUrl("auth/logout")?>">sair</a></span>
</div>
<div id="menuTopo">
    <div class="cAlign">
        <div id="logo"><img src="/images/logo2.png" /></div>
        <ul>
            <li><a class="agenda" href="<?php echo $this->baseUrl("auth/logout")?>" >AGENDA</a></li>
            <li><a class="mensagem" href="<?php echo $this->baseUrl("auth/logout")?>" >MENSAGEM</a></li>
            <li><a class="tarefa" href="<?php echo $this->baseUrl("auth/logout")?>" >TAREFA</a></li>
        </ul>
    </div>
</div>